title = "FabianHauser.ch"
base_url = "https://fabianhauser.ch"

# Build options
compile_sass = false
minify_html = false
ignored_content = [".gitignore", ".gitkeep"]

# Theme
theme = "tabi"
quick_navigation_buttons = true

# Search
build_search_index = true

# Feed
generate_feed = true
feed_limit = 40

# Taxanomy
taxonomies = [
  {name = "tags", feed = true}, # each tag will have its own feed
  {name = "tags"}, # you can have taxonomies with the same name in multiple languages
  {name = "categories", paginate_by = 5},  # 5 items per page for a term
]



[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "on"

[extra]
author = "Fabian Hauser"
menu = [
    { name = "about", url = "", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
#    { name = "travel", url = "travel", trailing_slash = true },
]

